# Generated by Django 6.0.6 on 2026-06-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Kenglik'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Uzunlik'),
        ),
    ]
