# Generated by Django 6.0.6 on 2026-06-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_supplier_latitude_supplier_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tuman'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Viloyat'),
        ),
    ]
