# Generated by Django 6.0.6 on 2026-06-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_add_supplier_region_district'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicinebatch',
            options={'ordering': ['expiry_date', 'batch_number'], 'verbose_name': 'Mahsulot partiyasi', 'verbose_name_plural': 'Mahsulot partiyalari'},
        ),
        migrations.AddField(
            model_name='medicine',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='SKU (Stock Keeping Unit)'),
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Barcode'),
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='batch_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Batch raqami'),
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Sertifikat'),
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='is_recalled',
            field=models.BooleanField(default=False, verbose_name='Recall qilingan'),
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='qr_code',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='QR kod'),
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='recall_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Recall sababi'),
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='recalled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Recall vaqti'),
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='storage_conditions',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Saqlash shartlari'),
        ),
    ]
