# Generated by Django 6.0.6 on 2026-06-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_alter_medicinebatch_options_medicine_sku_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['name'], name='medicines_m_name_61a774_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['category', 'is_active'], name='medicines_m_categor_d3b84e_idx'),
        ),
        migrations.AddIndex(
            model_name='medicinebatch',
            index=models.Index(fields=['expiry_date'], name='medicines_m_expiry__aeb79c_idx'),
        ),
        migrations.AddIndex(
            model_name='medicinebatch',
            index=models.Index(fields=['medicine', 'expiry_date'], name='medicines_m_medicin_806f19_idx'),
        ),
    ]
