# Generated by Django 5.0.6 on 2026-06-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0005_add_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='barcode',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Barcode'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='medicinebatch',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Barcode'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Faol'),
        ),
    ]
