# Generated by Django 6.0.6 on 2026-06-08 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Ombordagi miqdor')),
                ('min_quantity', models.IntegerField(default=10, verbose_name='Minimal miqdor')),
                ('max_quantity', models.IntegerField(blank=True, null=True, verbose_name='Maksimal miqdor')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Joylashuv')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('medicine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='medicines.medicine', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Inventar',
                'verbose_name_plural': 'Inventarlar',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_quantity', models.IntegerField(verbose_name='Haqiqiy miqdor')),
                ('system_quantity', models.IntegerField(verbose_name='Tizimdagi miqdor')),
                ('difference', models.IntegerField(editable=False, verbose_name='Farq')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('counted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kim sanagan')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_counts', to='medicines.medicine', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': "Inventar sanog'i",
                'verbose_name_plural': 'Inventar sanoqlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
