# Generated by Django 6.0.6 on 2026-06-19 04:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeofenceZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Zona nomi')),
                ('zone_type', models.CharField(choices=[('warehouse', 'Ombor'), ('pharmacy', 'Dorixona'), ('office', 'Ofis'), ('other', 'Boshqa')], default='warehouse', max_length=20, verbose_name='Zona turi')),
                ('latitude', models.FloatField(verbose_name='Kenglik')),
                ('longitude', models.FloatField(verbose_name='Uzunlik')),
                ('radius', models.IntegerField(default=100, verbose_name='Radius (metr)')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Manzil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_zones', to='companies.branch', verbose_name='Filial')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_zones', to='companies.company', verbose_name='Kompaniya')),
            ],
            options={
                'verbose_name': 'Geofence zona',
                'verbose_name_plural': 'Geofence zonalar',
                'ordering': ['company', 'branch', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', "Yillik ta'til"), ('sick', 'Kasal'), ('personal', 'Shaxsiy'), ('family', 'Oilaviy'), ('other', 'Boshqa')], max_length=20, verbose_name="Ta'til turi")),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('reason', models.TextField(verbose_name='Sabab')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Bekor qilingan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Holat')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqt')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Bekor qilish sababi')),
                ('document', models.FileField(blank=True, null=True, upload_to='leave_documents/', verbose_name='Hujjat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlagan')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='companies.company', verbose_name='Kompaniya')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "Ta'til so'rovi",
                'verbose_name_plural': "Ta'til so'rovlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Smena nomi')),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Tugash vaqti')),
                ('grace_period', models.IntegerField(default=15, verbose_name='Kechikish muddati (daqiqa)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='companies.branch', verbose_name='Filial')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='companies.company', verbose_name='Kompaniya')),
            ],
            options={
                'verbose_name': 'Smena',
                'verbose_name_plural': 'Smenalar',
                'ordering': ['company', 'branch', 'start_time'],
                'unique_together': {('company', 'branch', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_type', models.CharField(choices=[('check_in', 'Kelish'), ('check_out', 'Ketish')], max_length=20, verbose_name='Tur')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Vaqt')),
                ('status', models.CharField(choices=[('on_time', "O'z vaqtida"), ('late', 'Kechikkan'), ('early_leave', 'Erta ketgan'), ('overtime', "Qo'shimcha ish"), ('missed', 'Tushirib qoldirilgan')], default='on_time', max_length=20, verbose_name='Holat')),
                ('method', models.CharField(choices=[('manual', "Qo'lda"), ('qr', 'QR kod'), ('face', 'Yuz tanib olish'), ('auto', 'Avtomatik')], default='manual', max_length=20, verbose_name='Usul')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Kenglik')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Uzunlik')),
                ('is_within_geofence', models.BooleanField(default=False, verbose_name='Geofence ichida')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='attendance/', verbose_name='Rasm')),
                ('device_info', models.CharField(blank=True, max_length=500, null=True, verbose_name="Qurilma ma'lumoti")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('geofence_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.geofencezone', verbose_name='Geofence zona')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.shift', verbose_name='Smena')),
            ],
            options={
                'verbose_name': 'Davomat yozuvi',
                'verbose_name_plural': 'Davomat yozuvlari',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('status', models.CharField(choices=[('on_time', "O'z vaqtida"), ('late', 'Kechikkan'), ('early_leave', 'Erta ketgan'), ('overtime', "Qo'shimcha ish"), ('missed', 'Tushirib qoldirilgan')], default='on_time', max_length=20, verbose_name='Holat')),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Jami soat')),
                ('overtime_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Qo'shimcha soat")),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_check_in', to='attendance.attendancerecord', verbose_name='Kelish')),
                ('check_out', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_check_out', to='attendance.attendancerecord', verbose_name='Ketish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('geofence_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.geofencezone', verbose_name='Geofence zona')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.shift', verbose_name='Smena')),
            ],
            options={
                'verbose_name': 'Davomat sessiyasi',
                'verbose_name_plural': 'Davomat sessiyalari',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['user', 'timestamp'], name='attendance__user_id_da4f7d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['user', 'attendance_type', 'timestamp'], name='attendance__user_id_4f162c_idx'),
        ),
    ]
