# Generated by Django 5.0.6 on 2026-06-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='attendance_type',
            field=models.CharField(choices=[('check_in', 'Kelish'), ('check_out', 'Ketish')], db_index=True, max_length=20, verbose_name='Tur'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('on_time', "O'z vaqtida"), ('late', 'Kechikkan'), ('early_leave', 'Erta ketgan'), ('overtime', "Qo'shimcha ish"), ('missed', 'Tushirib qoldirilgan')], db_index=True, default='on_time', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='status',
            field=models.CharField(choices=[('on_time', "O'z vaqtida"), ('late', 'Kechikkan'), ('early_leave', 'Erta ketgan'), ('overtime', "Qo'shimcha ish"), ('missed', 'Tushirib qoldirilgan')], db_index=True, default='on_time', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Bekor qilingan'), ('cancelled', 'Bekor qilingan')], db_index=True, default='pending', max_length=20, verbose_name='Holat'),
        ),
    ]
