# Generated by Django 6.0.6 on 2026-06-08 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('low_stock', 'Mahsulot kamaygan'), ('expiry', 'Muddati tugayotgan'), ('income', 'Yangi kirim'), ('expense', 'Yangi chiqim'), ('system', 'Tizim'), ('medicine', 'Mahsulot')], max_length=20, verbose_name='Tur')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('is_global', models.BooleanField(default=False, verbose_name='Umumiy')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Havola')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_stock', models.BooleanField(default=True, verbose_name='Mahsulot kamayganda')),
                ('expiry', models.BooleanField(default=True, verbose_name='Muddati tugayotganda')),
                ('income', models.BooleanField(default=True, verbose_name='Yangi kirim')),
                ('expense', models.BooleanField(default=True, verbose_name='Yangi chiqim')),
                ('telegram', models.BooleanField(default=False, verbose_name='Telegram')),
                ('sms', models.BooleanField(default=False, verbose_name='SMS')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Bildirishnoma sozlamasi',
                'verbose_name_plural': 'Bildirishnoma sozlamalari',
            },
        ),
    ]
