# Generated by Django 5.0.6 on 2026-06-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationsetting_push_devicetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_global',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Umumiy'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name="O'qilgan"),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('low_stock', 'Mahsulot kamaygan'), ('expiry', 'Muddati tugayotgan'), ('income', 'Yangi kirim'), ('expense', 'Yangi chiqim'), ('system', 'Tizim'), ('medicine', 'Mahsulot')], db_index=True, max_length=20, verbose_name='Tur'),
        ),
    ]
