# Generated by Django 6.0.6 on 2026-06-08 06:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
        ('pharmacies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Narxi')),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=20, verbose_name='Jami summa')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Chiqim sababi')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Kim bergan')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_transactions', to='medicines.medicine', verbose_name='Mahsulot')),
                ('pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_transactions', to='pharmacies.pharmacy', verbose_name='Dorixona')),
            ],
            options={
                'verbose_name': 'Chiqim',
                'verbose_name_plural': 'Chiqimlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncomeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Narxi')),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=20, verbose_name='Jami summa')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/income/', verbose_name='Hujjat')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Kim qabul qilgan')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_transactions', to='medicines.medicine', verbose_name='Mahsulot')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_transactions', to='medicines.supplier', verbose_name='Yetkazib beruvchi')),
            ],
            options={
                'verbose_name': 'Kirim',
                'verbose_name_plural': 'Kirimlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('income', 'Kirim'), ('expense', 'Chiqim'), ('adjustment', 'Tuzatish')], max_length=20, verbose_name='Harakat turi')),
                ('quantity', models.IntegerField(verbose_name='Miqdor')),
                ('quantity_before', models.IntegerField(verbose_name='Oldingi miqdor')),
                ('quantity_after', models.IntegerField(verbose_name='Keyingi miqdor')),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Havola turi')),
                ('reference_id', models.IntegerField(blank=True, null=True, verbose_name='Havola ID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kim bajargan')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='medicines.medicine', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Inventar harakati',
                'verbose_name_plural': 'Inventar harakatlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
