# Generated by Django 6.0.6 on 2026-06-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetransaction',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qabul qiluvchi'),
        ),
    ]
