# Generated by Django 6.0.6 on 2026-06-19 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('medicines', '0004_alter_medicinebatch_options_medicine_sku_and_more'),
        ('warehouse', '0002_expensetransaction_recipient_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Bin nomi')),
                ('code', models.CharField(max_length=50, verbose_name='Bin kodi')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Barcode')),
                ('max_capacity', models.IntegerField(default=0, verbose_name="Maksimal sig'im")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Bin',
                'verbose_name_plural': 'Bin-lar',
                'ordering': ['shelf', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseRack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Rack nomi')),
                ('code', models.CharField(max_length=50, verbose_name='Rack kodi')),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Maksimal og'irlik (kg)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Rack',
                'verbose_name_plural': 'Racklar',
                'ordering': ['zone', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ombor nomi')),
                ('code', models.CharField(max_length=50, verbose_name='Ombor kodi')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Manzil')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='companies.branch', verbose_name='Filial')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='companies.company', verbose_name='Kompaniya')),
            ],
            options={
                'verbose_name': 'Ombor',
                'verbose_name_plural': 'Omborlar',
                'ordering': ['company', 'branch', 'name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.AddField(
            model_name='incometransaction',
            name='warehouse_bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_transactions', to='warehouse.warehousebin', verbose_name='Bin'),
        ),
        migrations.CreateModel(
            name='WarehouseShelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Shelf nomi')),
                ('code', models.CharField(max_length=50, verbose_name='Shelf kodi')),
                ('level', models.IntegerField(default=1, verbose_name='Sath')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='warehouse.warehouserack', verbose_name='Rack')),
            ],
            options={
                'verbose_name': 'Shelf',
                'verbose_name_plural': 'Shelf-lar',
                'ordering': ['rack', 'level', 'name'],
                'unique_together': {('rack', 'code')},
            },
        ),
        migrations.AddField(
            model_name='warehousebin',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='warehouse.warehouseshelf', verbose_name='Shelf'),
        ),
        migrations.CreateModel(
            name='WarehouseZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Zona nomi')),
                ('code', models.CharField(max_length=50, verbose_name='Zona kodi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='warehouse.warehouse', verbose_name='Ombor')),
            ],
            options={
                'verbose_name': 'Ombor zonasi',
                'verbose_name_plural': 'Ombor zonalari',
                'ordering': ['warehouse', 'name'],
                'unique_together': {('warehouse', 'code')},
            },
        ),
        migrations.AddField(
            model_name='warehouserack',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='warehouse.warehousezone', verbose_name='Zona'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Miqdor')),
                ('reserved_quantity', models.IntegerField(default=0, verbose_name='Zahiralangan miqdor')),
                ('available_quantity', models.IntegerField(default=0, editable=False, verbose_name='Mavjud miqdor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='medicines.medicinebatch', verbose_name='Batch')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='medicines.medicine', verbose_name='Mahsulot')),
                ('warehouse_bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='warehouse.warehousebin', verbose_name='Bin')),
            ],
            options={
                'verbose_name': 'Stok',
                'verbose_name_plural': 'Stoklar',
                'ordering': ['warehouse_bin', 'medicine'],
                'unique_together': {('warehouse_bin', 'medicine', 'batch')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='warehousebin',
            unique_together={('shelf', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='warehouserack',
            unique_together={('zone', 'code')},
        ),
    ]
