# Generated by Django 6.0.6 on 2026-06-19 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('medicines', '0004_alter_medicinebatch_options_medicine_sku_and_more'),
        ('orders', '0001_initial'),
        ('tasks', '0001_initial'),
        ('warehouse', '0003_warehousebin_warehouserack_warehouse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='picking_strategy',
            field=models.CharField(choices=[('fefo', 'FEFO — First Expiry, First Out'), ('fifo', 'FIFO — First In, First Out'), ('lifo', 'LIFO — Last In, First Out')], default='fefo', max_length=10, verbose_name='Komplektatsiya strategiyasi'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('income', 'Kirim'), ('expense', 'Chiqim'), ('adjustment', 'Tuzatish'), ('reserve', 'Zahiralash'), ('unreserve', 'Zahiradan chiqarish'), ('transfer', "Ko'chirish")], max_length=20, verbose_name='Harakat turi'),
        ),
        migrations.CreateModel(
            name='PickOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_number', models.CharField(max_length=50, unique=True, verbose_name='Komplektatsiya raqami')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_progress', 'Komplektatsiya'), ('picked', 'Komplektatsiya qilingan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Holat')),
                ('strategy', models.CharField(choices=[('fefo', 'FEFO — First Expiry, First Out'), ('fifo', 'FIFO — First In, First Out'), ('lifo', 'LIFO — Last In, First Out')], default='fefo', max_length=10, verbose_name='Strategiya')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan vaqt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugallangan vaqt')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_orders', to=settings.AUTH_USER_MODEL, verbose_name='Komplektator')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pick_orders', to=settings.AUTH_USER_MODEL, verbose_name='Kim yaratgan')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_orders', to='orders.order', verbose_name='Buyurtma')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_orders', to='tasks.task', verbose_name='Vazifa')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_orders', to='warehouse.warehouse', verbose_name='Ombor')),
            ],
            options={
                'verbose_name': "Komplektatsiya buyrug'i",
                'verbose_name_plural': 'Komplektatsiya buyruqlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.IntegerField(verbose_name='Talab qilingan miqdor')),
                ('picked_quantity', models.IntegerField(default=0, verbose_name='Komplektatsiya qilingan')),
                ('is_picked', models.BooleanField(default=False, verbose_name='Komplektatsiya qilingan')),
                ('picked_at', models.DateTimeField(blank=True, null=True, verbose_name='Komplektatsiya vaqti')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_items', to='medicines.medicinebatch', verbose_name='Batch')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_items', to='medicines.medicine', verbose_name='Mahsulot')),
                ('pick_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.pickorder', verbose_name="Komplektatsiya buyrug'i")),
                ('picked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picked_items', to=settings.AUTH_USER_MODEL, verbose_name='Kim komplektatsiya qilgan')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_items', to='warehouse.stock', verbose_name='Stok')),
                ('warehouse_bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_items', to='warehouse.warehousebin', verbose_name='Bin')),
            ],
            options={
                'verbose_name': 'Komplektatsiya mahsuloti',
                'verbose_name_plural': 'Komplektatsiya mahsulotlari',
                'ordering': ['pick_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PickWave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wave_number', models.CharField(max_length=50, unique=True, verbose_name="To'lqin raqami")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_progress', 'Komplektatsiya'), ('completed', 'Tugallangan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Holat')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan vaqt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugallangan vaqt')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_waves', to=settings.AUTH_USER_MODEL, verbose_name='Komplektator')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_waves', to='companies.branch', verbose_name='Filial')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_waves', to='companies.company', verbose_name='Kompaniya')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pick_waves', to=settings.AUTH_USER_MODEL, verbose_name='Kim yaratgan')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_waves', to='warehouse.warehouse', verbose_name='Ombor')),
            ],
            options={
                'verbose_name': "Komplektatsiya to'lqini",
                'verbose_name_plural': "Komplektatsiya to'lqinlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pickorder',
            name='wave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pick_orders', to='warehouse.pickwave', verbose_name="To'lqin"),
        ),
    ]
