# Generated by Django 6.0.6 on 2026-06-19 05:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0005_add_indexes'),
        ('pharmacies', '0003_pharmacy_approved_at_pharmacy_district_and_more'),
        ('warehouse', '0004_add_picking_models_v3'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expensetransaction',
            index=models.Index(fields=['medicine', 'created_at'], name='warehouse_e_medicin_38f227_idx'),
        ),
        migrations.AddIndex(
            model_name='expensetransaction',
            index=models.Index(fields=['pharmacy'], name='warehouse_e_pharmac_e26b28_idx'),
        ),
        migrations.AddIndex(
            model_name='incometransaction',
            index=models.Index(fields=['medicine', 'created_at'], name='warehouse_i_medicin_c33d8a_idx'),
        ),
        migrations.AddIndex(
            model_name='incometransaction',
            index=models.Index(fields=['supplier'], name='warehouse_i_supplie_754b22_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['medicine', 'movement_type'], name='warehouse_i_medicin_43dae6_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['created_at'], name='warehouse_i_created_f2d1e3_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['medicine', 'warehouse_bin'], name='warehouse_s_medicin_8c6263_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['batch'], name='warehouse_s_batch_i_2eb1d4_idx'),
        ),
    ]
