# Generated by Django 6.0.6 on 2026-06-08 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Yaratish'), ('UPDATE', 'Tahrirlash'), ('DELETE', "O'chirish"), ('LOGIN', 'Kirish'), ('LOGOUT', 'Chiqish'), ('EXPORT', 'Eksport'), ('IMPORT', 'Import'), ('BLOCK', 'Bloklash'), ('UNBLOCK', 'Blokdan chiqarish'), ('OTHER', 'Boshqa')], max_length=20, verbose_name='Harakat')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name="Ob'ekt ID")),
                ('data_before', models.JSONField(blank=True, null=True, verbose_name="Oldingi ma'lumot")),
                ('data_after', models.JSONField(blank=True, null=True, verbose_name="Keyingi ma'lumot")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='Qurilma')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Audit yozuvi',
                'verbose_name_plural': 'Audit yozuvlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
