# Generated by Django 5.0.6 on 2026-06-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Yaratish'), ('UPDATE', 'Tahrirlash'), ('DELETE', "O'chirish"), ('LOGIN', 'Kirish'), ('LOGOUT', 'Chiqish'), ('EXPORT', 'Eksport'), ('IMPORT', 'Import'), ('BLOCK', 'Bloklash'), ('UNBLOCK', 'Blokdan chiqarish'), ('OTHER', 'Boshqa')], db_index=True, max_length=20, verbose_name='Harakat'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Model'),
        ),
    ]
