apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shifoxona

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - backend.yaml
  - frontend.yaml
  - nginx.yaml
