apiVersion: v1
kind: Secret
metadata:
  name: shifoxona-secret
  namespace: shifoxona
type: Opaque
stringData:
  SECRET_KEY: "change-me-in-production"
  DB_PASSWORD: "postgres"
  DB_USER: "postgres"
  DB_NAME: "shifoxona_db"
