apiVersion: v1
kind: Secret
metadata:
  name: shifoxona-secret
  namespace: shifoxona
type: Opaque
data:
  SECRET_KEY: <base64-placeholder>
  DB_PASSWORD: <base64-placeholder>
  DB_USER: <base64-placeholder>
  DB_NAME: <base64-placeholder>
  REDIS_PASSWORD: <base64-placeholder>
