# Generated by Django 5.0.6 on 2026-06-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orders_orde_status_c6dd84_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlandi'), ('preparing', 'Tayyorlanmoqda'), ('shipped', "Yo'lga chiqdi"), ('delivered', 'Yetkazildi'), ('received', 'Dorixona qabul qildi'), ('cancelled', 'Bekor qilindi')], db_index=True, default='pending', max_length=20, verbose_name='Holati'),
        ),
    ]
