# Generated by Django 6.0.6 on 2026-06-08 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Dorixona nomi')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('responsible_person', models.CharField(max_length=255, verbose_name="Mas'ul shaxs")),
                ('responsible_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name="Mas'ul telefon")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Dorixona',
                'verbose_name_plural': 'Dorixonalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Dorixonadagi soni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_products', to='medicines.medicine', verbose_name='Mahsulot')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pharmacies.pharmacy', verbose_name='Dorixona')),
            ],
            options={
                'verbose_name': 'Dorixonadagi mahsulot',
                'verbose_name_plural': 'Dorixonadagi mahsulotlar',
                'ordering': ['pharmacy', 'medicine'],
                'unique_together': {('pharmacy', 'medicine')},
            },
        ),
    ]
