# Generated by Django 6.0.6 on 2026-06-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='responsible_phone',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Kenglik'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Uzunlik'),
        ),
    ]
