# Generated by Django 6.0.6 on 2026-06-09 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0002_remove_pharmacy_responsible_phone_pharmacy_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqt'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tuman'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pharmacies/', verbose_name='Dorixona rasmi'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Tasdiqlangan'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Viloyat'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='stir_or_license',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='STIR/Litsenziya raqami'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
    ]
