# Generated by Django 6.0.6 on 2026-06-19 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('company', 'Kompaniya'), ('branch', 'Filial'), ('department', "Bo'lim"), ('position', 'Lavozim'), ('user', 'Foydalanuvchi'), ('role', 'Rol'), ('medicine', 'Mahsulot'), ('category', 'Kategoriya'), ('supplier', 'Yetkazib beruvchi'), ('warehouse_zone', 'Ombor zonasi'), ('warehouse_rack', 'Rack'), ('warehouse_shelf', 'Shelf'), ('warehouse_bin', 'Bin'), ('batch', 'Batch'), ('inventory', 'Inventar'), ('order', 'Buyurtma'), ('delivery', 'Yetkazish'), ('pharmacy', 'Dorixona'), ('income', 'Kirim'), ('expense', 'Chiqim'), ('report', 'Hisobot'), ('notification', 'Bildirishnoma'), ('attendance', 'Davomat'), ('finance', 'Moliya'), ('employee', 'Xodim'), ('driver', 'Haydovchi'), ('geofencezone', 'Geofence zona'), ('shift', 'Smena'), ('attendancerecord', 'Davomat yozuvi'), ('attendancesession', 'Davomat sessiyasi'), ('leaverequest', "Ta'til so'rovi"), ('task', 'Vazifa'), ('taskcomment', 'Vazifa izohi'), ('taskattachment', 'Vazifa fayli'), ('chatroom', 'Chat xonasi'), ('chatmessage', 'Xabar')], max_length=100, verbose_name='Model')),
                ('action', models.CharField(choices=[('view', "Ko'rish"), ('create', 'Yaratish'), ('update', 'Tahrirlash'), ('delete', "O'chirish"), ('approve', 'Tasdiqlash'), ('export', 'Eksport')], max_length=50, verbose_name='Amal')),
                ('codename', models.CharField(max_length=200, verbose_name='Kod nomi')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Ruxsat',
                'verbose_name_plural': 'Ruxsatlar',
                'ordering': ['model_name', 'action'],
                'unique_together': {('model_name', 'action')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Rol nomi')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Rol kodi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('is_system', models.BooleanField(default=False, verbose_name='Tizim roli')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, to='rbac.permission', verbose_name='Ruxsatlar')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Rollar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='companies.branch', verbose_name='Filial')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='companies.company', verbose_name='Kompaniya')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='rbac.role', verbose_name='Rol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi roli',
                'verbose_name_plural': 'Foydalanuvchi rollari',
                'unique_together': {('user', 'role', 'company', 'branch')},
            },
        ),
    ]
