# Generated by Django 6.0.6 on 2026-06-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='model_name',
            field=models.CharField(choices=[('company', 'Kompaniya'), ('branch', 'Filial'), ('department', "Bo'lim"), ('position', 'Lavozim'), ('user', 'Foydalanuvchi'), ('role', 'Rol'), ('medicine', 'Mahsulot'), ('category', 'Kategoriya'), ('supplier', 'Yetkazib beruvchi'), ('warehouse_zone', 'Ombor zonasi'), ('warehouse_rack', 'Rack'), ('warehouse_shelf', 'Shelf'), ('warehouse_bin', 'Bin'), ('batch', 'Batch'), ('inventory', 'Inventar'), ('order', 'Buyurtma'), ('delivery', 'Yetkazish'), ('pharmacy', 'Dorixona'), ('income', 'Kirim'), ('expense', 'Chiqim'), ('report', 'Hisobot'), ('notification', 'Bildirishnoma'), ('attendance', 'Davomat'), ('finance', 'Moliya'), ('employee', 'Xodim'), ('driver', 'Haydovchi'), ('geofencezone', 'Geofence zona'), ('shift', 'Smena'), ('attendancerecord', 'Davomat yozuvi'), ('attendancesession', 'Davomat sessiyasi'), ('leaverequest', "Ta'til so'rovi"), ('task', 'Vazifa'), ('taskcomment', 'Vazifa izohi'), ('taskattachment', 'Vazifa fayli'), ('chatroom', 'Chat xonasi'), ('chatmessage', 'Xabar'), ('pickwave', "Komplektatsiya to'lqini"), ('pickorder', "Komplektatsiya buyrug'i"), ('pickorderitem', 'Komplektatsiya mahsuloti')], max_length=100, verbose_name='Model'),
        ),
    ]
