# Generated by Django 6.0.6 on 2026-06-09 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('assigned', 'Kuryer biriktirildi'), ('picked', 'Olindi'), ('in_transit', "Yo'lda"), ('delivered', 'Yetkazildi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20, verbose_name='Holati')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Biriktirilgan vaqt')),
                ('picked_at', models.DateTimeField(blank=True, null=True, verbose_name='Olingan vaqt')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Yetkazilgan vaqt')),
                ('courier_lat', models.FloatField(blank=True, null=True, verbose_name='Kuryer kenglik')),
                ('courier_lng', models.FloatField(blank=True, null=True, verbose_name='Kuryer uzunlik')),
                ('courier_location_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Joylashuv yangilangan vaqt')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Kuryer')),
            ],
            options={
                'verbose_name': 'Yetkazib berish',
                'verbose_name_plural': 'Yetkazib berishlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
