# Generated by Django 6.0.6 on 2026-06-19 04:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Kenglik')),
                ('longitude', models.FloatField(verbose_name='Uzunlik')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='Aniqlik')),
                ('speed', models.FloatField(blank=True, null=True, verbose_name='Tezlik (km/h)')),
                ('bearing', models.FloatField(blank=True, null=True, verbose_name="Yo'nalish")),
                ('battery_level', models.IntegerField(blank=True, null=True, verbose_name='Batareya (%)')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Qayd etilgan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_logs', to=settings.AUTH_USER_MODEL, verbose_name='Kuryer')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to='delivery.delivery', verbose_name='Yetkazib berish')),
            ],
            options={
                'verbose_name': 'Joylashuv tarixi',
                'verbose_name_plural': 'Joylashuv tarixi',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['delivery', 'recorded_at'], name='delivery_de_deliver_917772_idx')],
            },
        ),
    ]
