# Generated by Django 6.0.6 on 2026-06-19 05:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_add_location_log'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status'], name='delivery_de_status_6efeaa_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['courier', 'status'], name='delivery_de_courier_e5ae05_idx'),
        ),
    ]
