# Generated by Django 6.0.6 on 2026-06-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('operator', 'Operator'), ('pharmacy', 'Dorixona')], default='operator', max_length=20, verbose_name='Lavozim'),
        ),
    ]
