# Generated by Django 6.0.6 on 2026-06-19 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='companies.branch', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='companies.company', verbose_name='Kompaniya'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='companies.department', verbose_name="Bo'lim"),
        ),
        migrations.AddField(
            model_name='user',
            name='position_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='companies.position', verbose_name='Lavozim'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('operator', 'Operator'), ('warehouse', 'Omborchi'), ('driver', 'Haydovchi'), ('finance', 'Moliya'), ('pharmacy', 'Dorixona')], default='operator', max_length=20, verbose_name='Lavozim'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='Xodim ID')),
                ('hire_date', models.DateField(verbose_name='Ishga qabul sanasi')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Maosh')),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pasport raqami')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Yashash manzili')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Favqulodda kontakt')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Favqulodda telefon')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='companies.branch', verbose_name='Filial')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='companies.company', verbose_name='Kompaniya')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='companies.department', verbose_name="Bo'lim")),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='companies.position', verbose_name='Lavozim')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['company', 'branch', 'employee_id'],
            },
        ),
    ]
