# Generated by Django 6.0.6 on 2026-06-19 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('orders', '0001_initial'),
        ('warehouse', '0003_warehousebin_warehouserack_warehouse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Vazifa sarlavhasi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('task_type', models.CharField(choices=[('pick', 'Komplektatsiya'), ('pack', 'Qadoqlash'), ('load', 'Yuklash'), ('deliver', 'Yetkazish'), ('count', 'Inventarizatsiya'), ('receiving', 'Qabul qilish'), ('maintenance', 'Texnik xizmat'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Vazifa turi')),
                ('priority', models.CharField(choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori'), ('urgent', 'Shoshilinch')], default='medium', max_length=20, verbose_name='Prioritet')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_progress', 'Bajarilmoqda'), ('completed', 'Bajarilgan'), ('cancelled', 'Bekor qilingan'), ('on_hold', "To'xtatilgan")], default='pending', max_length=20, verbose_name='Holat')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Bajarish muddati')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan vaqt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugallangan vaqt')),
                ('estimated_minutes', models.IntegerField(default=0, verbose_name='Taxminiy vaqt (daqiqa)')),
                ('actual_minutes', models.IntegerField(default=0, verbose_name='Haqiqiy vaqt (daqiqa)')),
                ('is_private', models.BooleanField(default=False, verbose_name='Shaxsiy')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Topshiriq beruvchi')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Bajaruvchi')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='companies.branch', verbose_name='Filial')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='companies.company', verbose_name='Kompaniya')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='orders.order', verbose_name='Buyurtma')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='warehouse.warehouse', verbose_name='Ombor')),
            ],
            options={
                'verbose_name': 'Vazifa',
                'verbose_name_plural': 'Vazifalar',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_attachments/', verbose_name='Fayl')),
                ('filename', models.CharField(max_length=500, verbose_name='Fayl nomi')),
                ('file_size', models.IntegerField(default=0, verbose_name='Fayl hajmi (bayt)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task', verbose_name='Vazifa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Vazifa fayli',
                'verbose_name_plural': 'Vazifa fayllari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Matn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task', verbose_name='Vazifa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Vazifa izohi',
                'verbose_name_plural': 'Vazifa izohlari',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'assigned_to'], name='tasks_task_status_d50342_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['company', 'branch', 'status'], name='tasks_task_company_846a9e_idx'),
        ),
    ]
