# Generated by Django 5.0.6 on 2026-06-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori'), ('urgent', 'Shoshilinch')], db_index=True, default='medium', max_length=20, verbose_name='Prioritet'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('pick', 'Komplektatsiya'), ('pack', 'Qadoqlash'), ('load', 'Yuklash'), ('deliver', 'Yetkazish'), ('count', 'Inventarizatsiya'), ('receiving', 'Qabul qilish'), ('maintenance', 'Texnik xizmat'), ('other', 'Boshqa')], db_index=True, default='other', max_length=20, verbose_name='Vazifa turi'),
        ),
    ]
