# Generated by Django 6.0.6 on 2026-06-19 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kompaniya nomi')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Qisqa nom')),
                ('inn', models.CharField(max_length=50, unique=True, verbose_name='INN/STIR')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('license_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Litsenziya raqami')),
                ('license_expiry', models.DateField(blank=True, null=True, verbose_name='Litsenziya amal qilish muddati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kompaniya',
                'verbose_name_plural': 'Kompaniyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Filial nomi')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Filial kodi')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='companies.company', verbose_name='Kompaniya')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiallar',
                'ordering': ['company', 'name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Bo'lim nomi")),
                ('code', models.CharField(max_length=50, verbose_name="Bo'lim kodi")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='companies.branch', verbose_name='Filial')),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
                'ordering': ['branch', 'name'],
                'unique_together': {('branch', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Lavozim')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Lavozim kodi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='companies.department')),
            ],
            options={
                'verbose_name': 'Lavozim',
                'verbose_name_plural': 'Lavozimlar',
                'ordering': ['name'],
            },
        ),
    ]
