# Generated by Django 6.0.6 on 2026-06-08 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Hisobot nomi')),
                ('report_type', models.CharField(choices=[('income', 'Kirim hisoboti'), ('expense', 'Chiqim hisoboti'), ('inventory', 'Inventar hisoboti'), ('expiry', 'Muddati tugayotgan mahsulotlar'), ('pharmacy', 'Dorixona hisoboti'), ('general', 'Umumiy hisobot')], max_length=20, verbose_name='Hisobot turi')),
                ('file_format', models.CharField(choices=[('xlsx', 'Excel'), ('csv', 'CSV'), ('pdf', 'PDF')], default='xlsx', max_length=10, verbose_name='Format')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Fayl')),
                ('filters', models.JSONField(blank=True, default=dict, null=True, verbose_name='Filtrlar')),
                ('is_ready', models.BooleanField(default=False, verbose_name='Tayyor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kim yaratgan')),
            ],
            options={
                'verbose_name': 'Hisobot',
                'verbose_name_plural': 'Hisobotlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
