# Generated by Django 5.0.6 on 2026-06-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name="O'qilgan"),
        ),
    ]
